stlab.adobe.com
Documentation
Overview
Building ASL
Documentation
Library Wiki Docs
Indices
Browse Perforce
More Info
Release Notes
Wiki
Site Search
License
Success Stories
Contributors
Media
Download
Perforce Depots
Support
ASL SourceForge Home
Mailing Lists
Discussion Forums
Report Bugs
Suggest Features
Contribute to ASL
RSS
Short-text news
Full-text news
File releases
Other Adobe Projects
Adobe Air
Adobe GIL
Adobe Labs
Adobe Media Gallery
Adobe XMP
Tamarin project
(Mozilla Foundation)
Other Resources
Boost
RIAForge
SGI STL
dng_color_spec Class Reference
#include <dng_color_spec.h>
Public Member Functions
dng_color_spec (const dng_negative &negative, const dng_camera_profile *profile)
uint32 Channels () const
void SetWhiteXY (const dng_xy_coord &white)
const dng_xy_coord & WhiteXY () const
const dng_vector & CameraWhite () const
const dng_matrix & CameraToPCS () const
dng_xy_coord NeutralToXY (const dng_vector &neutral)
Detailed Description
Color transform taking into account white point and camera calibration and individual calibration from DNG negative.
Constructor & Destructor Documentation
dng_color_spec::dng_color_spec (const dng_negative & negative, const dng_camera_profile * profile)
Read calibration info from DNG negative and construct a dng_color_spec.
References dng_negative::AnalogBalance(), dng_camera_profile::CalibrationTemperature1(), dng_camera_profile::CalibrationTemperature2(), dng_negative::CameraCalibration1(), dng_negative::CameraCalibration2(), dng_camera_profile::ColorMatrix1(), dng_camera_profile::ColorMatrix2(), dng_camera_profile::ForwardMatrix1(), dng_camera_profile::ForwardMatrix2(), dng_camera_profile::HasColorMatrix2(), dng_camera_profile::IsValid(), dng_camera_profile::NormalizeForwardMatrix(), dng_camera_profile::ReductionMatrix1(), dng_camera_profile::ReductionMatrix2(), ThrowBadFormat(), ThrowProgramError(), and dng_camera_profile::WasStubbed().
Member Function Documentation
const dng_matrix & dng_color_spec::CameraToPCS () const
Getter for camera to Profile Connection Space color transform.
Return values:
A transform that takes into account all camera calibration transforms and white point.
References DNG_ASSERT.
const dng_vector & dng_color_spec::CameraWhite () const
Return white point in camera native color coordinates.
Return values:
A dng_vector with components ranging from 0.0 to 1.0 that is normalized such that one component is equal to 1.0 .
References DNG_ASSERT.
uint32 dng_color_spec::Channels () const [inline]
Number of channels used for this color transform. Three for most cameras.
dng_xy_coord dng_color_spec::NeutralToXY (const dng_vector & neutral)
Return the XY value to use for SetWhiteXY for a given camera color space coordinate as the white point.
Parameters:
neutral A camera color space value to use for white point. Components range from 0.0 to 1.0 and should be normalized such that the largest value is 1.0 .
Return values:
White point in XY space that makes neutral map to this XY value as closely as possible.
void dng_color_spec::SetWhiteXY (const dng_xy_coord & white)
Setter for white point. Value is as XY colorspace coordinate.
Parameters:
white White point to set as an XY value.
const dng_xy_coord & dng_color_spec::WhiteXY () const
Getter for white point. Value is as XY colorspace coordinate.
Return values:
XY value of white point.
References DNG_ASSERT.
The documentation for this class was generated from the following files:
dng_color_spec.h
dng_color_spec.cpp
Company |
Online Privacy Policy |
Terms of Use |
Contact Us |
Accessibility |
Report Piracy |
Permissions & Trademarks |
Product License Agreements |
Send Feedback
Copyright © 2006-2009 Adobe Systems Incorporated.
Use of this website signifies your agreement to the Terms of Use and Online Privacy Policy.
Search powered by Google