stlab.adobe.com
Documentation
Overview
Building ASL
Documentation
Library Wiki Docs
Indices
Browse Perforce
More Info
Release Notes
Wiki
Site Search
License
Success Stories
Contributors
Media
Download
Perforce Depots
Support
ASL SourceForge Home
Mailing Lists
Discussion Forums
Report Bugs
Suggest Features
Contribute to ASL
RSS
Short-text news
Full-text news
File releases
Other Adobe Projects
Adobe Air
Adobe GIL
Adobe Labs
Adobe Media Gallery
Adobe XMP
Tamarin project
(Mozilla Foundation)
Other Resources
Boost
RIAForge
SGI STL
dng_memory_block Class Reference
Class to provide resource acquisition is instantiation discipline for image buffers and other larger memory allocations.
#include <dng_memory.h>
Inherited by dng_malloc_block.
Public Member Functions
uint32 LogicalSize () const
void * Buffer ()
const void * Buffer () const
char * Buffer_char ()
const char * Buffer_char () const
uint8 * Buffer_uint8 ()
const uint8 * Buffer_uint8 () const
uint16 * Buffer_uint16 ()
const uint16 * Buffer_uint16 () const
int16 * Buffer_int16 ()
const int16 * Buffer_int16 () const
uint32 * Buffer_uint32 ()
const uint32 * Buffer_uint32 () const
int32 * Buffer_int32 ()
const int32 * Buffer_int32 () const
real32 * Buffer_real32 ()
const real32 * Buffer_real32 () const
real64 * Buffer_real64 ()
const real64 * Buffer_real64 () const
Protected Member Functions
dng_memory_block (uint32 logicalSize)
uint32 PhysicalSize ()
void SetBuffer (void *p)
Detailed Description
Class to provide resource acquisition is instantiation discipline for image buffers and other larger memory allocations.
This class requires a dng_memory_allocator for allocation.
Member Function Documentation
const void* dng_memory_block::Buffer () const [inline]
Return pointer to allocated memory as a const void *.
Return values:
const void * valid for as many bytes as were allocated.
void* dng_memory_block::Buffer () [inline]
Return pointer to allocated memory as a void *..
Return values:
void * valid for as many bytes as were allocated.
Referenced by Buffer_char(), Buffer_int16(), Buffer_int32(), Buffer_real32(), Buffer_real64(), Buffer_uint16(), Buffer_uint32(), and Buffer_uint8().
const char* dng_memory_block::Buffer_char () const [inline]
Return pointer to allocated memory as a const char *.
Return values:
const char * valid for as many bytes as were allocated.
References Buffer().
char* dng_memory_block::Buffer_char () [inline]
Return pointer to allocated memory as a char *.
Return values:
char * valid for as many bytes as were allocated.
References Buffer().
const int16* dng_memory_block::Buffer_int16 () const [inline]
Return pointer to allocated memory as a const int16 *.
Return values:
const int16 * valid for as many bytes as were allocated.
References Buffer().
int16* dng_memory_block::Buffer_int16 () [inline]
Return pointer to allocated memory as a int16 *.
Return values:
int16 * valid for as many bytes as were allocated.
References Buffer().
const int32* dng_memory_block::Buffer_int32 () const [inline]
Return pointer to allocated memory as a const int32 *.
Return values:
const int32 * valid for as many bytes as were allocated.
References Buffer().
int32* dng_memory_block::Buffer_int32 () [inline]
Return pointer to allocated memory as a int32 *.
Return values:
int32 * valid for as many bytes as were allocated.
References Buffer().
const real32* dng_memory_block::Buffer_real32 () const [inline]
Return pointer to allocated memory as a const real32 *.
Return values:
const real32 * valid for as many bytes as were allocated.
References Buffer().
real32* dng_memory_block::Buffer_real32 () [inline]
Return pointer to allocated memory as a real32 *.
Return values:
real32 * valid for as many bytes as were allocated.
References Buffer().
const real64* dng_memory_block::Buffer_real64 () const [inline]
Return pointer to allocated memory as a const real64 *.
Return values:
const real64 * valid for as many bytes as were allocated.
References Buffer().
real64* dng_memory_block::Buffer_real64 () [inline]
Return pointer to allocated memory as a real64 *.
Return values:
real64 * valid for as many bytes as were allocated.
References Buffer().
const uint16* dng_memory_block::Buffer_uint16 () const [inline]
Return pointer to allocated memory as a const uint16 *.
Return values:
const uint16 * valid for as many bytes as were allocated.
References Buffer().
uint16* dng_memory_block::Buffer_uint16 () [inline]
Return pointer to allocated memory as a uint16 *.
Return values:
uint16 * valid for as many bytes as were allocated.
References Buffer().
const uint32* dng_memory_block::Buffer_uint32 () const [inline]
Return pointer to allocated memory as a const uint32 *.
Return values:
const uint32 * valid for as many bytes as were allocated.
References Buffer().
uint32* dng_memory_block::Buffer_uint32 () [inline]
Return pointer to allocated memory as a uint32 *.
Return values:
uint32 * valid for as many bytes as were allocated.
References Buffer().
const uint8* dng_memory_block::Buffer_uint8 () const [inline]
Return pointer to allocated memory as a const uint8 *.
Return values:
const uint8 * valid for as many bytes as were allocated.
References Buffer().
uint8* dng_memory_block::Buffer_uint8 () [inline]
Return pointer to allocated memory as a uint8 *.
Return values:
uint8 * valid for as many bytes as were allocated.
References Buffer().
Referenced by dng_memory_stream::CopyToStream().
uint32 dng_memory_block::LogicalSize () const [inline]
Getter for available size, in bytes, of memory block.
Return values:
size in bytes of available memory in memory block.
The documentation for this class was generated from the following file:
dng_memory.h
Company |
Online Privacy Policy |
Terms of Use |
Contact Us |
Accessibility |
Report Piracy |
Permissions & Trademarks |
Product License Agreements |
Send Feedback
Copyright © 2006-2009 Adobe Systems Incorporated.
Use of this website signifies your agreement to the Terms of Use and Online Privacy Policy.
Search powered by Google