stlab.adobe.com
Documentation
Overview
Building ASL
Documentation
Library Wiki Docs
Indices
Browse Perforce
More Info
Release Notes
Wiki
Site Search
License
Success Stories
Contributors
Media
Download
Perforce Depots
Support
ASL SourceForge Home
Mailing Lists
Discussion Forums
Report Bugs
Suggest Features
Contribute to ASL
RSS
Short-text news
Full-text news
File releases
Other Adobe Projects
Adobe Air
Adobe GIL
Adobe Labs
Adobe Media Gallery
Adobe XMP
Tamarin project
(Mozilla Foundation)
Other Resources
Boost
RIAForge
SGI STL
dng_sniffer_task Class Reference
Class to establish scope of a named subtask in DNG processing.
#include <dng_abort_sniffer.h>
Public Member Functions
dng_sniffer_task (dng_abort_sniffer *sniffer, const char *name=NULL, real64 fract=0.0)
void Sniff ()
void UpdateProgress (real64 fract)
void UpdateProgress (uint32 done, uint32 total)
void Finish ()
Signal task completed for progress purposes.
Detailed Description
Class to establish scope of a named subtask in DNG processing.
Instances of this class are intended to be stack allocated.
Constructor & Destructor Documentation
dng_sniffer_task::dng_sniffer_task (dng_abort_sniffer * sniffer, const char * name = NULL, real64 fract = 0.0) [inline]
Inform a sniffer of a subtask in DNG processing.
Parameters:
sniffer The sniffer associated with the host on which this processing is occurring.
name The name of this subtask as a NUL terminated string.
fract Percentage of total processing this task is expected to take, from 0.0 to 1.0 .
References dng_abort_sniffer::StartTask().
Member Function Documentation
void dng_sniffer_task::Sniff () [inline]
Check for pending user cancellation or other abort. ThrowUserCanceled will be called if one is pending.
References dng_abort_sniffer::SniffForAbort().
void dng_sniffer_task::UpdateProgress (uint32 done, uint32 total) [inline]
Update progress on this subtask.
Parameters:
done Amount of task completed in arbitrary integer units.
total Total size of task in same arbitrary integer units as done.
References UpdateProgress().
void dng_sniffer_task::UpdateProgress (real64 fract) [inline]
Update progress on this subtask.
Parameters:
fract Percentage of processing completed on current task, from 0.0 to 1.0 .
References dng_abort_sniffer::UpdateProgress().
Referenced by Finish(), and UpdateProgress().
The documentation for this class was generated from the following file:
dng_abort_sniffer.h
Company |
Online Privacy Policy |
Terms of Use |
Contact Us |
Accessibility |
Report Piracy |
Permissions & Trademarks |
Product License Agreements |
Send Feedback
Copyright © 2006-2009 Adobe Systems Incorporated.
Use of this website signifies your agreement to the Terms of Use and Online Privacy Policy.
Search powered by Google