stlab.adobe.com
Documentation
Overview
Building ASL
Documentation
Library Wiki Docs
Indices
Browse Perforce
More Info
Release Notes
Wiki
Site Search
License
Success Stories
Contributors
Media
Download
Perforce Depots
Support
ASL SourceForge Home
Mailing Lists
Discussion Forums
Report Bugs
Suggest Features
Contribute to ASL
RSS
Short-text news
Full-text news
File releases
Other Adobe Projects
Adobe Air
Adobe GIL
Adobe Labs
Adobe Media Gallery
Adobe XMP
Tamarin project
(Mozilla Foundation)
Other Resources
Boost
RIAForge
SGI STL
dng_abort_sniffer Class Reference
Class for signaling user cancellation and receiving progress updates.
#include <dng_abort_sniffer.h>
Public Member Functions
dng_priority Priority () const
Getter for priority level.
void SetPriority (dng_priority priority)
Setter for priority level.
void SniffNoPriorityWait ()
Static Public Member Functions
static void SniffForAbort (dng_abort_sniffer *sniffer)
Protected Member Functions
virtual void Sniff ()=0
virtual void StartTask (const char *name, real64 fract)
virtual void EndTask ()
Signals the end of the innermost task that has been started.
virtual void UpdateProgress (real64 fract)
Friends
class dng_sniffer_task
Detailed Description
Class for signaling user cancellation and receiving progress updates.
DNG SDK clients should derive a host application specific implementation from this class.
Member Function Documentation
virtual void dng_abort_sniffer::Sniff () [protected, pure virtual]
Should be implemented by derived classes to check for an user cancellation.
Referenced by SniffForAbort().
void dng_abort_sniffer::SniffForAbort (dng_abort_sniffer * sniffer) [static]
Check for pending user cancellation or other abort. ThrowUserCanceled will be called if one is pending. This static method is provided as a convenience for quickly testing for an abort and throwing an exception if one is pending.
Parameters:
sniffer The dng_sniffer to test for a pending abort. Can be NULL, in which case there an abort is never signalled.
References Priority(), and Sniff().
Referenced by dng_stream::Flush(), dng_stream::Get(), dng_area_task::ProcessOnThread(), dng_stream::Put(), and dng_sniffer_task::Sniff().
void dng_abort_sniffer::StartTask (const char * name, real64 fract) [protected, virtual]
Signals the start of a named task withn processing in the DNG SDK. Tasks may be nested.
Parameters:
name of the task
fract Percentage of total processing this task is expected to take. From 0.0 to 1.0 .
Referenced by dng_sniffer_task::dng_sniffer_task().
void dng_abort_sniffer::UpdateProgress (real64 fract) [protected, virtual]
Signals progress made on current task.
Parameters:
fract percentage of processing completed on current task. From 0.0 to 1.0 .
Referenced by dng_sniffer_task::UpdateProgress().
The documentation for this class was generated from the following files:
dng_abort_sniffer.h
dng_abort_sniffer.cpp
Company |
Online Privacy Policy |
Terms of Use |
Contact Us |
Accessibility |
Report Piracy |
Permissions & Trademarks |
Product License Agreements |
Send Feedback
Copyright © 2006-2009 Adobe Systems Incorporated.
Use of this website signifies your agreement to the Terms of Use and Online Privacy Policy.
Search powered by Google