stlab.adobe.com
Documentation
Overview
Building ASL
Documentation
Library Wiki Docs
Indices
Browse Perforce
More Info
Release Notes
Wiki
Site Search
License
Success Stories
Contributors
Media
Download
Perforce Depots
Support
ASL SourceForge Home
Mailing Lists
Discussion Forums
Report Bugs
Suggest Features
Contribute to ASL
RSS
Short-text news
Full-text news
File releases
Other Adobe Projects
Adobe Air
Adobe GIL
Adobe Labs
Adobe Media Gallery
Adobe XMP
Tamarin project
(Mozilla Foundation)
Other Resources
Boost
RIAForge
SGI STL
dng_date_time Class Reference
Class for holding a date/time and converting to and from relevant date/time formats.
#include <dng_date_time.h>
Public Member Functions
dng_date_time ()
Construct an invalid date/time.
dng_date_time (uint32 year, uint32 month, uint32 day, uint32 hour, uint32 minute, uint32 second)
bool IsValid () const
bool NotValid () const
bool operator== (const dng_date_time &dt) const
Equal operator.
bool operator!= (const dng_date_time &dt) const
void Clear ()
Set date to an invalid value.
bool Parse (const char *s)
Public Attributes
uint32 fYear
uint32 fMonth
uint32 fDay
uint32 fHour
uint32 fMinute
uint32 fSecond
Detailed Description
Class for holding a date/time and converting to and from relevant date/time formats.
Constructor & Destructor Documentation
dng_date_time::dng_date_time (uint32 year, uint32 month, uint32 day, uint32 hour, uint32 minute, uint32 second)
Construct a date/time with specific values.
Parameters:
year Year to use as actual integer value, such as 2006.
month Month to use from 1 - 12, where 1 is January.
day Day of month to use from 1 -31, where 1 is the first.
hour Hour of day to use from 0 - 23, where 0 is midnight.
minute Minute of hour to use from 0 - 59.
second Second of minute to use from 0 - 59.
Member Function Documentation
bool dng_date_time::IsValid () const
Predicate to determine if a date is valid.
Return values:
true if all fields are within range.
Referenced by LocalTimeZone(), NotValid(), and Parse().
bool dng_date_time::NotValid () const [inline]
Predicate to determine if a date is invalid.
Return values:
true if any field is out of range.
References IsValid().
bool dng_date_time::Parse (const char * s)
Parse an EXIF format date string.
Parameters:
s Input date string to parse.
Return values:
true if date was parsed successfully and date is valid.
References IsValid().
The documentation for this class was generated from the following files:
dng_date_time.h
dng_date_time.cpp
Company |
Online Privacy Policy |
Terms of Use |
Contact Us |
Accessibility |
Report Piracy |
Permissions & Trademarks |
Product License Agreements |
Send Feedback
Copyright © 2006-2009 Adobe Systems Incorporated.
Use of this website signifies your agreement to the Terms of Use and Online Privacy Policy.
Search powered by Google