stlab.adobe.com
Documentation
Overview
Building ASL
Documentation
Library Wiki Docs
Indices
Browse Perforce
More Info
Release Notes
Wiki
Site Search
License
Success Stories
Contributors
Media
Download
Perforce Depots
Support
ASL SourceForge Home
Mailing Lists
Discussion Forums
Report Bugs
Suggest Features
Contribute to ASL
RSS
Short-text news
Full-text news
File releases
Other Adobe Projects
Adobe Air
Adobe GIL
Adobe Labs
Adobe Media Gallery
Adobe XMP
Tamarin project
(Mozilla Foundation)
Other Resources
Boost
RIAForge
SGI STL
dng_memory_allocator Class Reference
Interface for dng_memory_block allocator.
#include <dng_memory.h>
Public Member Functions
virtual dng_memory_block * Allocate (uint32 size)
Detailed Description
Interface for dng_memory_block allocator.
Member Function Documentation
dng_memory_block * dng_memory_allocator::Allocate (uint32 size) [virtual]
Allocate a dng_memory block.
Parameters:
size Number of bytes in memory block.
Return values:
A dng_memory_block with at least size bytes of valid storage.
Exceptions:
dng_exception with fErrorCode equal to dng_error_memory.
References ThrowMemoryFull().
Referenced by dng_host::Allocate(), dng_stream::AsMemoryBlock(), dng_1d_table::Initialize(), and dng_filter_task::Start().
The documentation for this class was generated from the following files:
dng_memory.h
dng_memory.cpp
Company |
Online Privacy Policy |
Terms of Use |
Contact Us |
Accessibility |
Report Piracy |
Permissions & Trademarks |
Product License Agreements |
Send Feedback
Copyright © 2006-2009 Adobe Systems Incorporated.
Use of this website signifies your agreement to the Terms of Use and Online Privacy Policy.
Search powered by Google