stlab.adobe.com
Documentation
Overview
Building ASL
Documentation
Library Wiki Docs
Indices
Browse Perforce
More Info
Release Notes
Wiki
Site Search
License
Success Stories
Contributors
Media
Download
Perforce Depots
Support
ASL SourceForge Home
Mailing Lists
Discussion Forums
Report Bugs
Suggest Features
Contribute to ASL
RSS
Short-text news
Full-text news
File releases
Other Adobe Projects
Adobe Air
Adobe GIL
Adobe Labs
Adobe Media Gallery
Adobe XMP
Tamarin project
(Mozilla Foundation)
Other Resources
Boost
RIAForge
SGI STL
dng_render Class Reference
Class used to render digital negative to displayable image.
#include <dng_render.h>
Public Member Functions
dng_render (dng_host &host, const dng_negative &negative)
void SetWhiteXY (const dng_xy_coord &white)
const dng_xy_coord WhiteXY () const
void SetExposure (real64 exposure)
real64 Exposure () const
void SetShadows (real64 shadows)
real64 Shadows () const
void SetToneCurve (const dng_1d_function &curve)
const dng_1d_function & ToneCurve () const
void SetFinalSpace (const dng_color_space &space)
const dng_color_space & FinalSpace () const
void SetFinalPixelType (uint32 type)
uint32 FinalPixelType () const
void SetMaximumSize (uint32 size)
uint32 MaximumSize () const
virtual dng_image * Render ()
Protected Attributes
dng_host & fHost
const dng_negative & fNegative
dng_xy_coord fWhiteXY
real64 fExposure
real64 fShadows
const dng_1d_function * fToneCurve
const dng_color_space * fFinalSpace
uint32 fFinalPixelType
uint32 fMaximumSize
Detailed Description
Class used to render digital negative to displayable image.
Constructor & Destructor Documentation
dng_render::dng_render (dng_host & host, const dng_negative & negative)
Construct a rendering instance that will be used to convert a given digital negative.
Parameters:
host The host to use for memory allocation, progress updates, and abort testing.
negative The digital negative to convert to a displayable image.
References AutoPtr< T >::Get(), dng_1d_identity::Get(), and AutoPtr< T >::Reset().
Member Function Documentation
real64 dng_render::Exposure () const [inline]
Get exposure compensation.
Return values:
Compensation value in stops, positive or negative.
uint32 dng_render::FinalPixelType () const [inline]
Get pixel type of final image data. Can be ttByte (default), ttShort, or ttFloat.
Return values:
Pixel type to use.
Referenced by Render().
const dng_color_space& dng_render::FinalSpace () const [inline]
Get final color space in which resulting image data should be represented.
Return values:
Color space to use.
Referenced by Render().
uint32 dng_render::MaximumSize () const [inline]
Get maximum dimension, in pixels, of resulting image. If the final image would have either dimension larger than this maximum, the larger of the two dimensions is set to this maximum size and the smaller dimension is adjusted to preserve the image's aspect ratio.
Return values:
Maximum allowed size.
Referenced by Render().
dng_image * dng_render::Render () [virtual]
Actually render a digital negative to a displayable image. Input digital negative is passed to the constructor of this dng_render class.
Return values:
The final resulting image.
References dng_negative::AspectRatio(), dng_negative::DefaultCropArea(), dng_negative::DefaultFinalHeight(), dng_negative::DefaultFinalWidth(), FinalPixelType(), FinalSpace(), AutoPtr< T >::Get(), dng_color_space::IsMonochrome(), dng_host::Make_dng_image(), MaximumSize(), dng_host::PerformAreaTask(), dng_image::PixelType(), dng_image::Planes(), AutoPtr< T >::Release(), and AutoPtr< T >::Reset().
void dng_render::SetExposure (real64 exposure) [inline]
Set exposure compensation.
Parameters:
exposure Compensation value in stops, positive or negative.
void dng_render::SetFinalPixelType (uint32 type) [inline]
Set pixel type of final image data. Can be ttByte (default), ttShort, or ttFloat.
Parameters:
type Pixel type to use.
void dng_render::SetFinalSpace (const dng_color_space & space) [inline]
Set final color space in which resulting image data should be represented. (See dng_color_space.h for possible values.)
Parameters:
space Color space to use.
void dng_render::SetMaximumSize (uint32 size) [inline]
Set maximum dimension, in pixels, of resulting image. If final image would have either dimension larger than maximum, the larger of the two dimensions is set to this maximum size and the smaller dimension is adjusted to preserve aspect ratio.
Parameters:
size Maximum size to allow.
void dng_render::SetShadows (real64 shadows) [inline]
Set shadow clip amount.
Parameters:
shadows Shadow clip amount.
void dng_render::SetToneCurve (const dng_1d_function & curve) [inline]
Set custom tone curve for conversion.
Parameters:
curve 1D function that defines tone mapping to use during conversion.
void dng_render::SetWhiteXY (const dng_xy_coord & white) [inline]
Set the white point to be used for conversion.
Parameters:
white White point to use.
real64 dng_render::Shadows () const [inline]
Get shadow clip amount.
Return values:
Shadow clip amount.
const dng_1d_function& dng_render::ToneCurve () const [inline]
Get custom tone curve for conversion.
Return values:
1D function that defines tone mapping to use during conversion.
const dng_xy_coord dng_render::WhiteXY () const [inline]
Get the white point to be used for conversion.
Return values:
White point to use.
The documentation for this class was generated from the following files:
dng_render.h
dng_render.cpp
Company |
Online Privacy Policy |
Terms of Use |
Contact Us |
Accessibility |
Report Piracy |
Permissions & Trademarks |
Product License Agreements |
Send Feedback
Copyright © 2006-2009 Adobe Systems Incorporated.
Use of this website signifies your agreement to the Terms of Use and Online Privacy Policy.
Search powered by Google