stlab.adobe.com
Documentation
Overview
Building ASL
Documentation
Library Wiki Docs
Indices
Browse Perforce
More Info
Release Notes
Wiki
Site Search
License
Success Stories
Contributors
Media
Download
Perforce Depots
Support
ASL SourceForge Home
Mailing Lists
Discussion Forums
Report Bugs
Suggest Features
Contribute to ASL
RSS
Short-text news
Full-text news
File releases
Other Adobe Projects
Adobe Air
Adobe GIL
Adobe Labs
Adobe Media Gallery
Adobe XMP
Tamarin project
(Mozilla Foundation)
Other Resources
Boost
RIAForge
SGI STL
dng_info Class Reference
Top-level structure of DNG file with access to metadata.
#include <dng_info.h>
Public Member Functions
virtual void Parse (dng_host &host, dng_stream &stream)
virtual void PostParse (dng_host &host)
Must be called immediately after a successful Parse operation.
virtual bool IsValidDNG ()
Public Attributes
uint64 fTIFFBlockOffset
uint64 fTIFFBlockOriginalOffset
bool fBigEndian
uint32 fMagic
AutoPtr< dng_exif > fExif
AutoPtr< dng_shared > fShared
int32 fMainIndex
uint32 fIFDCount
AutoPtr< dng_ifd > fIFD [kMaxSubIFDs+1]
uint32 fChainedIFDCount
AutoPtr< dng_ifd > fChainedIFD [kMaxChainedIFDs]
Protected Member Functions
virtual void ValidateMagic ()
virtual void ParseTag (dng_host &host, dng_stream &stream, dng_exif *exif, dng_shared *shared, dng_ifd *ifd, uint32 parentCode, uint32 tagCode, uint32 tagType, uint32 tagCount, uint64 tagOffset, int64 offsetDelta)
virtual bool ValidateIFD (dng_stream &stream, uint64 ifdOffset, int64 offsetDelta)
virtual void ParseIFD (dng_host &host, dng_stream &stream, dng_exif *exif, dng_shared *shared, dng_ifd *ifd, uint64 ifdOffset, int64 offsetDelta, uint32 parentCode)
virtual bool ParseMakerNoteIFD (dng_host &host, dng_stream &stream, uint64 ifdSize, uint64 ifdOffset, int64 offsetDelta, uint64 minOffset, uint64 maxOffset, uint32 parentCode)
virtual void ParseMakerNote (dng_host &host, dng_stream &stream, uint32 makerNoteCount, uint64 makerNoteOffset, int64 offsetDelta, uint64 minOffset, uint64 maxOffset)
virtual void ParseSonyPrivateData (dng_host &host, dng_stream &stream, uint32 count, uint64 oldOffset, uint64 newOffset)
virtual void ParseDNGPrivateData (dng_host &host, dng_stream &stream)
Protected Attributes
uint32 fMakerNoteNextIFD
Detailed Description
Top-level structure of DNG file with access to metadata.
See DNG 1.1.0 specification for information on member fields of this class.
Member Function Documentation
bool dng_info::IsValidDNG () [virtual]
Test validity of DNG data.
Return values:
true if stream provided a valid DNG.
References AutoPtr< T >::Get().
void dng_info::Parse (dng_host & host, dng_stream & stream) [virtual]
Read dng_info from a dng_stream
Parameters:
host DNG host used for progress updating, abort testing, buffer allocation, etc.
stream Stream to read DNG data from.
References AutoPtr< T >::Get(), dng_stream::Get_uint16(), dng_stream::Get_uint32(), dng_camera_profile::IsValid(), kMaxChainedIFDs, kMaxSubIFDs, dng_stream::Length(), dng_host::Make_dng_exif(), dng_host::Make_dng_ifd(), dng_host::Make_dng_shared(), dng_camera_profile::Parse(), dng_stream::Position(), dng_stream::PositionInOriginalFile(), AutoPtr< T >::Reset(), dng_stream::SetBigEndian(), dng_stream::SetLittleEndian(), dng_stream::SetReadPosition(), and ThrowBadFormat().
The documentation for this class was generated from the following files:
dng_info.h
dng_info.cpp
Company |
Online Privacy Policy |
Terms of Use |
Contact Us |
Accessibility |
Report Piracy |
Permissions & Trademarks |
Product License Agreements |
Send Feedback
Copyright © 2006-2009 Adobe Systems Incorporated.
Use of this website signifies your agreement to the Terms of Use and Online Privacy Policy.
Search powered by Google