stlab.adobe.com
Documentation
Overview
Building ASL
Documentation
Library Wiki Docs
Indices
Browse Perforce
More Info
Release Notes
Wiki
Site Search
License
Success Stories
Contributors
Media
Download
Perforce Depots
Support
ASL SourceForge Home
Mailing Lists
Discussion Forums
Report Bugs
Suggest Features
Contribute to ASL
RSS
Short-text news
Full-text news
File releases
Other Adobe Projects
Adobe Air
Adobe GIL
Adobe Labs
Adobe Media Gallery
Adobe XMP
Tamarin project
(Mozilla Foundation)
Other Resources
Boost
RIAForge
SGI STL
dng_date_time_storage_info Class Reference
Store file offset from which date was read.
#include <dng_date_time.h>
Public Member Functions
dng_date_time_storage_info ()
The default constructor initializes to an invalid state.
dng_date_time_storage_info (uint64 offset, dng_date_time_format format)
Construct with file offset and date format.
bool IsValid () const
uint64 Offset () const
dng_date_time_format Format () const
Detailed Description
Store file offset from which date was read.
Used internally by Adobe to update date in original file.
Warning:
Use at your own risk.
Member Function Documentation
dng_date_time_format dng_date_time_storage_info::Format () const
Get for format date was originally stored in file. Throws a dng_error_unknown exception if offset is invalid.
Exceptions:
dng_exception with fErrorCode equal to dng_error_unknown if offset is not valid.
References IsValid(), and ThrowProgramError().
bool dng_date_time_storage_info::IsValid () const
Predicate to determine if an offset is valid.
Return values:
true if offset is valid.
Referenced by Format(), and Offset().
uint64 dng_date_time_storage_info::Offset () const
Getter for offset in file.
Exceptions:
dng_exception with fErrorCode equal to dng_error_unknown if offset is not valid.
References IsValid(), and ThrowProgramError().
The documentation for this class was generated from the following files:
dng_date_time.h
dng_date_time.cpp
Company |
Online Privacy Policy |
Terms of Use |
Contact Us |
Accessibility |
Report Piracy |
Permissions & Trademarks |
Product License Agreements |
Send Feedback
Copyright © 2006-2009 Adobe Systems Incorporated.
Use of this website signifies your agreement to the Terms of Use and Online Privacy Policy.
Search powered by Google