stlab.adobe.com
Documentation
Overview
Building ASL
Documentation
Library Wiki Docs
Indices
Browse Perforce
More Info
Release Notes
Wiki
Site Search
License
Success Stories
Contributors
Media
Download
Perforce Depots
Support
ASL SourceForge Home
Mailing Lists
Discussion Forums
Report Bugs
Suggest Features
Contribute to ASL
RSS
Short-text news
Full-text news
File releases
Other Adobe Projects
Adobe Air
Adobe GIL
Adobe Labs
Adobe Media Gallery
Adobe XMP
Tamarin project
(Mozilla Foundation)
Other Resources
Boost
RIAForge
SGI STL
dng_1d_function Class Reference
A 1D floating-point function.
#include <dng_1d_function.h>
Public Member Functions
virtual bool IsIdentity () const
Returns true if this function is the map x -> y such that x == y for all x . That is if Evaluate(x) == x for all x.
virtual real64 Evaluate (real64 x) const =0
virtual real64 EvaluateInverse (real64 y) const
Detailed Description
A 1D floating-point function.
The domain (input) is always from 0.0 to 1.0, while the range (output) can be an arbitrary interval.
Member Function Documentation
virtual real64 dng_1d_function::Evaluate (real64 x) const [pure virtual]
Return the mapping for value x. This method must be implemented by a derived class of dng_1d_function and the derived class determines the lookup method and function used.
Parameters:
x A value between 0.0 and 1.0 (inclusive).
Return values:
Mapped value for x
Implemented in dng_1d_identity, dng_1d_concatenate, dng_1d_inverse, dng_function_GammaEncode_sRGB, dng_function_GammaEncode_1_8, dng_function_GammaEncode_2_2, dng_noise_function, dng_function_exposure_ramp, dng_function_exposure_tone, dng_tone_curve_acr3_default, and dng_function_gamma_encode.
Referenced by dng_1d_concatenate::Evaluate(), dng_1d_inverse::EvaluateInverse(), EvaluateInverse(), dng_color_space::GammaEncode(), and dng_1d_table::Initialize().
real64 dng_1d_function::EvaluateInverse (real64 y) const [virtual]
Return the reverse mapped value for y. This method can be implemented by derived classes. The default implementation uses Newton's method to solve for x such that Evaluate(x) == y.
Parameters:
y A value to reverse map. Should be within the range of the function implemented by this dng_1d_function .
Return values:
A value x such that Evaluate(x) == y (to very close approximation).
Reimplemented in dng_1d_identity, dng_1d_concatenate, dng_1d_inverse, dng_function_GammaEncode_sRGB, dng_function_GammaEncode_1_8, dng_function_GammaEncode_2_2, and dng_tone_curve_acr3_default.
References Evaluate().
Referenced by dng_1d_inverse::Evaluate(), dng_1d_concatenate::EvaluateInverse(), and dng_color_space::GammaDecode().
The documentation for this class was generated from the following files:
dng_1d_function.h
dng_1d_function.cpp
Company |
Online Privacy Policy |
Terms of Use |
Contact Us |
Accessibility |
Report Piracy |
Permissions & Trademarks |
Product License Agreements |
Send Feedback
Copyright © 2006-2009 Adobe Systems Incorporated.
Use of this website signifies your agreement to the Terms of Use and Online Privacy Policy.
Search powered by Google